version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks: 
      - overlay
  test:
    ports: 
      - "7000:7000"
    build: .
    depends_on:
        - "web"
    networks: 
      - overlay
    command: ["./wait-for-it.sh", "web:8080", "--", "npm", "test"]

networks:
  overlay:
